### ISSUE TITLE
multiExpand doesn't seem to be working

### ISSUE THREAD

**Issue by dungle-scrubs** [ShivamJoker/React-fast-accordion#6]
Adding `multiExpand={false}` (when added in the provided CodeSandbox demo) doesn't seem to be limiting the accordion to only one open item at a time.

**Comment by ShivamJoker** [comment]
Can you share the updated sandbox with the latest version of the library.

**Comment by dungle-scrubs** [comment]
Hey @ShivamJoker, thanks, I incorrectly assumed that the demo in the readme was the latest version, but it's a full version behind.  I checked the latest version and it works great.

**Comment by ShivamJoker** [comment]
No problem glad you figured it out
